name: circle_devs_official
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.1
  firebase_auth: ^0.18.4+1 
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.11.0
  http: ^0.12.2
  transparent_image: ^1.0.0
  image_picker: ^0.6.7+17
  path_provider: ^1.6.24
  firebase_messaging: ^7.0.3
  bottom_navy_bar: ^5.6.0

# firebase_auth: ^0.15.5+3
# firebase_storage: ^3.1.1
# cloud_firestore: ^0.13.0+1
# image_picker: ^0.6.2+3 
# google_sign_in: ^4.1.1
# firebase_storage: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/login/

